---
stages:
  - build

docker_build:
  stage: build
  image: docker:20.10.22-alpine3.17
  rules:
    - if: "$CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH"
  services:
    - docker:20.10.22-dind-alpine3.17
  variables:
    KITCHEN_SALT_VERSION: "0.7.2"
    TEST_KITCHEN_VERSION: "3.5.0"
  script:
    - echo "${DOCKERUB_PASSWORD}" | docker login -u ${DOCKERHUB_USER} --password-stdin
    - "docker build .
      --tag ${DOCKERHUB_ORG}/${DOCKERHUB_IMAGE}:salt-${KITCHEN_SALT_VERSION}_test-${KITCHEN_TEST_VERSION}
      --tag ${DOCKERHUB_ORG}/${DOCKERHUB_IMAGE}:latest
      --build-arg KITCHEN_SALT_VERSION=${KITCHEN_SALT_VERSION}
      --build-arg TEST_KITCHEN_VERSION=${TEST_KITCHEN_VERSION}"
    - docker push ${DOCKERHUB_ORG}/${DOCKERHUB_IMAGE}:${KITCHEN_SALT_VERSION}_test-${KITCHEN_TEST_VERSION}
    - docker push ${DOCKERHUB_ORG}/${DOCKERHUB_IMAGE}:latest
    - docker rmi ${DOCKERHUB_ORG}/${DOCKERHUB_IMAGE}:${KITCHEN_SALT_VERSION}_test-${KITCHEN_TEST_VERSION}
    - docker rmi ${DOCKERHUB_ORG}/${DOCKERHUB_IMAGE}:latest
